_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.4
        t:
            "1":
                - 2
                - 3
                - 55
                - 105
            "2":
                - 2
                - 3
                - 55
                - 105
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.10.4
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation_fn:
    value: relu
batch_size:
    value: 64
epochs:
    value: 10
hidden_size:
    value: 32
lr:
    value: 0.0001
n_hidden:
    value: 5
optimizer:
    value: nadam
weight_decay:
    value: 0
weight_initialization:
    value: xavier
