wandb_version: 1

activation_fn:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 128
lr:
  value: 0.001
n_hidden:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_initialization:
  value: xavier
