wandb_version: 1

activation_fn:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hidden_size:
  value: 32
lr:
  value: 0.001
n_hidden:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_initialization:
  value: xavier
