wandb_version: 1

activation_fn:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_size:
  value: 64
lr:
  value: 0.0001
n_hidden:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0.5
weight_initialization:
  value: random
