wandb_version: 1

activation_fn:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
hidden_size:
  value: 128
lr:
  value: 0.0001
n_hidden:
  value: 5
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_initialization:
  value: xavier
