wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_size:
  value: 128
lr:
  value: 0.001
n_hidden:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_initialization:
  value: xavier
