_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.4
        t:
            "1":
                - 2
                - 3
                - 55
                - 105
            "2":
                - 2
                - 3
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.4
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation_function:
    value: sigmoid
batch_size:
    value: 16
epochs:
    value: 10
hidden_layer_size:
    value: 128
learning_rate:
    value: 0.0001
num_hidden_layers:
    value: 4
optimizer:
    value: adam
weight_decay:
    value: 0.5
weight_initialization:
    value: xavier
