wandb_version: 1

activation_fn:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 10
hidden_size:
  value: 128
lr:
  value: 0.001
n_hidden:
  value: 3
optimizer:
  value: nesterov
weight_decay:
  value: 0.0005
weight_initialization:
  value: random
