wandb_version: 1

activation_fn:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hidden_size:
  value: 64
lr:
  value: 0.0001
n_hidden:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_initialization:
  value: xavier
