wandb_version: 1

activation_fn:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
hidden_size:
  value: 64
lr:
  value: 0.001
n_hidden:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0
weight_initialization:
  value: random
