wandb_version: 1

activation_fn:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 32
lr:
  value: 0.0001
n_hidden:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_initialization:
  value: xavier
