wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0.5
weight_initialization:
  value: random
