wandb_version: 1

activation_function:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 128
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 5
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
weight_initialization:
  value: random
