wandb_version: 1

activation_function:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 32
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 4
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_initialization:
  value: xavier
