method: bayes  # Can be "grid", "random", or "bayes"
metric:
  name: val_accuracy  # Change this if you're optimizing something else
  goal: maximize

parameters:
  epochs:
    values: [5, 10]
  n_hidden:
    values: [3, 4, 5]
  hidden_size:
    values: [32, 64, 128]
  weight_decay:
    values: [0, 0.0005, 0.5]
  lr:
    values: [0.001, 0.0001]
  optimizer:
    values: ["sgd", "momentum", "nesterov", "rmsprop", "adam", "nadam"]
  batch_size:
    values: [16, 32, 64]
  weight_initialization:
    values: ["random", "xavier"]
  activation_fn:
    values: ["sigmoid", "tanh", "relu"]
